# Generated by Django 4.0.5 on 2022-06-15 03:57

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        validators=[django.core.validators.RegexValidator("[0-9a-f]64")],
                    ),
                ),
                ("content", models.TextField()),
                (
                    "signature",
                    models.CharField(
                        max_length=128,
                        validators=[django.core.validators.RegexValidator("[0-9a-f]128")],
                    ),
                ),
                ("last_modified", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Peer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField(db_index=True, unique=True, verbose_name="URL")),
            ],
        ),
    ]
