#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

export PYTHONUNBUFFERED=1

uv sync --all-groups
uv run python manage.py migrate
uv run python manage.py loaddata admin_interface_theme_uswds.json

echo "Bootstrap completed!"
echo "To initialize an admin account, run:"
echo "tools/manage createsuperuser"
echo ""
echo "To launch the server, run:"
echo "tools/start"
