#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

export PYTHONUNBUFFERED=1

uv run --no-dev python manage.py collectstatic --noinput
uv run --no-dev python manage.py migrate
exec uv run --no-dev gunicorn letsdance.wsgi "$@"
