#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

source venv/bin/activate
pip-compile --allow-unsafe --generate-hashes requirements/requirements.in --output-file requirements/requirements.txt "$@"
pip-compile --allow-unsafe --generate-hashes requirements/requirements-dev.in --output-file requirements/requirements-dev.txt "$@"
